import "oaidl.idl";
import "ocidl.idl";
import "IOberonOleObject.idl";

[ uuid(EB6CD3E2-C1C9-416e-9466-0C40B8CD9165),
	version(1.0),
	helpstring("ETH Oberon, OLE PlugIns 1.0 Type Library") ]

library OberonOlePlugInLib {
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[ uuid(EB6CD3E1-C1C9-416e-9466-0C40B8CD9165),
		helpstring("ETH Oberon, OLE PlugIns Class") ]

	coclass OberonOlePlugIn {
		[ default ] interface IOberonOleObject;
		[ default, source ] dispinterface IOberonOleEvent;
	};
};
